services:
  api:
    image: ai-find-dotnet-demo-api-development
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "5000:8085"
    networks:
      - cdp-tenant
    volumes:
      - ./AiFindDotnetDemoApi:/home/dotnet/app/AiFindDotnetDemoApi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mongodb
  
  mongodb:
    image: mongo:6.0.13
    ports:
      - "27017:27017"
    networks:
      - cdp-tenant
    volumes:
      - mongodb:/data

volumes:
  mongodb:

networks:
  cdp-tenant:
    driver: bridge
